name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Укажите версию Python, которую вы хотите использовать

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Установка зависимостей из файла requirements.txt

    - name: Run script
      run: |
        python main.py  # Запускает основной скрипт

    - name: Run tests
      run: |
        pytest test_main.py  # Запускает тесты
